# This file was generated by GoReleaser. DO NOT EDIT.
cask "howdoi" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/WMcKibbin/howdoi/releases/download/v#{version}/howdoi_#{version}_darwin_amd64.tar.gz"
      sha256 "f0037fcf7f6aa51d1177627734852d5e4185d0c35b7d825ac59235ce3a8e4f52"
    end
    on_arm do
      url "https://github.com/WMcKibbin/howdoi/releases/download/v#{version}/howdoi_#{version}_darwin_arm64.tar.gz"
      sha256 "2ac24a4e2f9ceadc0ffccde5a866566d432f0dbc0a0b52bba2196e6f0012f99f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/WMcKibbin/howdoi/releases/download/v#{version}/howdoi_#{version}_linux_amd64.tar.gz"
      sha256 "465b84e21d755351023a9969e07e3da7e74796ef38e1fc623cb42f83590b7091"
    end
    on_arm do
      url "https://github.com/WMcKibbin/howdoi/releases/download/v#{version}/howdoi_#{version}_linux_arm64.tar.gz"
      sha256 "93352d2fcf108f6d0d18becc3402c65908f52e9b1ef82aca51c00e07150ae0ca"
    end
  end

  name "howdoi"
  desc "AI-powered command-line assistant"
  homepage "https://github.com/WMcKibbin/howdoi"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "howdoi"

  # No zap stanza required

end
